position_moves = {
    '.........': (0, 1, 2, 3, 4, 5, 6, 7, 8),
    '......X..': (8,),
    '.......X.': (0, 3, 6, 8),
    '........X': (0, 2, 4, 6),
    '..O...X..': (0, 4),
    '...O...X.': (0, 1, 2, 4, 5, 6, 8),
    '....X..O.': (2, 6, 8),
    '....O.X..': (0, 2, 7),
    '....O..X.': (6,),
    '.....O.X.': (6, 8),
    '......XO.': (4, 5, 8),
    '......X.O': (0, 1, 2, 3, 4, 5, 7),
    '......OX.': (2, 4, 5, 8),
    '......O.X': (0, 1, 2, 3, 4, 5, 7),
    '.......XO': (0, 1, 2, 4, 5, 6),
    '.......OX': (0, 1, 2, 4, 5, 6),
    '..X.X..O.': (3,),
    '..X.O.X..': (8,),
    '..X..O.X.': (8,),
    '..X...XO.': (8,),
    '..X...X.O': (1, 3, 5, 7),
    '..OX..X..': (0, 7, 8),
    '..O.X.X..': (5,),
    '..O.X..X.': (0,),
    '..O..X.X.': (0, 4),
    '..O...XX.': (0,),
    '..O...X.X': (0, 4),
    '...X.O.X.': (8,),
    '...X..OX.': (8,),
    '...X...XO': (0, 1, 2, 4, 5, 6),
    '...OX..X.': (0, 6),
    '...O.X.X.': (0, 6),
    '...O..XX.': (0,),
    '...O...XX': (0, 2, 4, 6),
    '....XX.O.': (6,),
    '....XOX..': (8,),
    '....XO.X.': (8,),
    '....X.XO.': (5,),
    '....X.X.O': (5,),
    '....X.OX.': (3, 8),
    '....X..XO': (0, 1, 5, 6),
    '....X..OX': (0,),
    '....OXX..': (2, 3),
    '....OX.X.': (2,),
    '....O.XX.': (0,),
    '....O.X.X': (2,),
    '....O..XX': (3,),
    '.....XOX.': (1, 3, 8),
    '.....X.XO': (0, 4, 6),
    '.....OXX.': (0,),
    '.....O.XX': (3,),
    '......XXO': (0,),
    '......XOX': (2,),
    '......OXX': (3,),
    'O.X.O.X..': (8,),
    'O.O.X.X..': (5,),
    '.O.X.O.X.': (8,),
    '.O.O.X.X.': (6,),
    '..XX.O.O.': (4,),
    '..XOX..O.': (8,),
    '..XO.X.O.': (8,),
    '..XO.OX..': (8,),
    '..XO.O.X.': (0, 6),
    '..XO..XO.': (8,),
    '..X.XO.O.': (3,),
    '..X.X.OO.': (3,),
    '..X.X..OO': (3,),
    '..X.OX.O.': (1, 8),
    '..X.OOX..': (8,),
    '..X.OO.X.': (6,),
    '..X.O.XO.': (8,),
    '..X.O.X.O': (0,),
    '..X.O.OX.': (5,),
    '..X..OXO.': (8,),
    '..X..OOX.': (4,),
    '..X..O.XO': (1,),
    '..X..O.OX': (6,),
    '..X...XOO': (3,),
    '..OXX..O.': (0, 6),
    '..OXO.X..': (7,),
    '..OXO..X.': (8,),
    '..OX.XO..': (8,),
    '..OX.X.O.': (0, 1, 6, 8),
    '..OX.OX..': (7,),
    '..OX.O.X.': (8,),
    '..OX..XO.': (0, 1, 4, 5, 8),
    '..OX..X.O': (0, 1, 4, 5),
    '..OX..OX.': (8,),
    '..OOX.X..': (5,),
    '..OOX..X.': (0, 6),
    '..OO.XX..': (4,),
    '..OO.X.X.': (4,),
    '..OO..XX.': (0,),
    '..OO..X.X': (4,),
    '..O.XXO..': (8,),
    '..O.XX.O.': (6,),
    '..O.XOX..': (0,),
    '..O.XO.X.': (0, 8),
    '..O.X.XO.': (5,),
    '..O.X.X.O': (5,),
    '..O.X.OX.': (8,),
    '..O.X.O.X': (0,),
    '..O.X..XO': (6,),
    '..O.X..OX': (0,),
    '..O.OXX..': (3,),
    '..O.OX.X.': (3,),
    '..O.O.XX.': (0,),
    '..O.O.X.X': (3,),
    '..O.O..XX': (3,),
    '..O..XOX.': (8,),
    '..O..X.XO': (6,),
    '..O..OXX.': (0,),
    '..O..O.XX': (3,),
    '..O...XXO': (0,),
    '..O...XOX': (4, 5),
    '..O...OXX': (3,),
    '...XO.OX.': (8,),
    '...X.OOX.': (8,),
    '...X.O.XO': (1,),
    '...X..OXO': (2,),
    '...OXO.X.': (0,),
    '...OX.XO.': (5,),
    '...OX.OX.': (0, 1, 2, 5, 8),
    '...OX..XO': (6,),
    '...OOX.X.': (2,),
    '...OO.XX.': (0,),
    '...OO..XX': (2,),
    '...O.XXO.': (4,),
    '...O.XOX.': (1, 2, 4, 8),
    '...O.X.XO': (6,),
    '...O.X.OX': (1,),
    '...O.OXX.': (0,),
    '...O.O.XX': (0, 6),
    '...O..XXO': (0,),
    '...O..XOX': (2,),
    '...O..OXX': (1, 2, 4, 5),
    '....XXOO.': (0,),
    '....XX.OO': (6,),
    '....XOXO.': (2, 8),
    '....XOX.O': (1,),
    '....XOOX.': (3, 8),
    '....XO.XO': (1,),
    '....XO.OX': (0,),
    '....X.XOO': (5,),
    '....X.OXO': (2,),
    '....X.OOX': (0,),
    '....OXXO.': (8,),
    '....OXX.O': (0,),
    '....OXOX.': (8,),
    '....OXO.X': (1,),
    '....OX.XO': (0,),
    '....OX.OX': (1,),
    '....OOXX.': (0,),
    '....OOX.X': (2,),
    '....OO.XX': (3,),
    '....O.XXO': (0,),
    '....O.XOX': (2,),
    '....O.OXX': (3,),
    '.....XOXO': (2,),
    '.....OXXO': (0,),
    '.....OXOX': (2,),
    '.....OOXX': (3,),
    'O.X.XOX..': (1, 3, 7, 8),
    'O.X.X.XO.': (1, 3, 5, 8),
    'O.X.X.X.O': (1, 3, 5, 7),
    'O.X.X.OX.': (3,),
    'O.X.O.XX.': (8,),
    'O.O.X.XX.': (1,),
    'O.O.X.X.X': (1,),
    '.XO.X.OX.': (8,),
    '.XO.O.XX.': (3,),
    '.X.XO.OX.': (5,),
    '.OXO.X.X.': (6,),
    '.OX.XO.X.': (8,),
    '.OX.X.XO.': (0, 3, 5, 8),
    '.OX.X.OX.': (3,),
    '.OX.OX.X.': (6, 8),
    '.OX.O.XX.': (0, 3, 5, 8),
    '.OOX.X.X.': (0,),
    '.OO.XX.X.': (0,),
    '.OO.X.XX.': (0,),
    '.O.XO.XX.': (0, 2, 5, 8),
    '.O.X.XOX.': (8,),
    '.O.X.X.XO': (0, 2),
    '.O.X.OXX.': (8,),
    '.O.OXX.X.': (6,),
    '.O.OX.XX.': (0, 2, 5, 8),
    '.O.O.XXX.': (0, 2, 4, 8),
    '.O.O.X.XX': (2,),
    '..XXOX.O.': (0,),
    '..XXOO.X.': (6,),
    '..XXO.XO.': (8,),
    '..XXO.OX.': (5,),
    '..XX.XOO.': (0,),
    '..XX.X.OO': (4,),
    '..XX.OXO.': (0, 1, 4, 8),
    '..XX.OOX.': (4,),
    '..XX.O.XO': (1,),
    '..XX.O.OX': (0, 1, 4, 6),
    '..XOXX.O.': (8,),
    '..XOXOX..': (8,),
    '..XOXO.X.': (0, 8),
    '..XOX.XO.': (8,),
    '..XOX.OX.': (0, 1, 8),
    '..XOX..XO': (0, 1, 5, 6),
    '..XOX..OX': (0, 1, 5, 6),
    '..XOOXX..': (8,),
    '..XOOX.X.': (0, 1, 6, 8),
    '..XOO.XX.': (0, 1, 5, 8),
    '..XO.XXO.': (8,),
    '..XO.XX.O': (7,),
    '..XO.XOX.': (0, 1, 8),
    '..XO.X.XO': (0, 6),
    '..XO.X.OX': (0, 1, 4, 6),
    '..XO.OXX.': (0, 1, 4, 8),
    '..XO.O.XX': (6,),
    '..XO..XXO': (0,),
    '..X.XXOO.': (0,),
    '..X.XX.OO': (3,),
    '..X.XOXO.': (0, 1, 3, 8),
    '..X.XOX.O': (1,),
    '..X.XOOX.': (3,),
    '..X.XO.XO': (1,),
    '..X.XO.OX': (0, 1, 3, 6),
    '..X.X.XOO': (3,),
    '..X.X.OXO': (3,),
    '..X.X.OOX': (0,),
    '..X.OXXO.': (8,),
    '..X.OXX.O': (0,),
    '..X.OXOX.': (1, 8),
    '..X.OX.XO': (0,),
    '..X.OX.OX': (0, 1, 3, 6),
    '..X.OOXX.': (0, 1, 3, 8),
    '..X.OO.XX': (6,),
    '..X.O.XXO': (0,),
    '..X.O.OXX': (5,),
    '..X..XOXO': (0, 1, 3, 4),
    '..X..OXXO': (1,),
    '..X..OOXX': (4,),
    '..OXXXO..': (8,),
    '..OXXX.O.': (6,),
    '..OXXOX..': (1,),
    '..OXXO.X.': (8,),
    '..OXX.XO.': (5,),
    '..OXX.X.O': (5,),
    '..OXX.OX.': (8,),
    '..OXX..XO': (6,),
    '..OXX..OX': (0,),
    '..OXOXX..': (0,),
    '..OXOX.X.': (8,),
    '..OXO.XX.': (0, 1, 5, 8),
    '..OXO.X.X': (7,),
    '..OX.XXO.': (4,),
    '..OX.XX.O': (4,),
    '..OX.XOX.': (8,),
    '..OX.XO.X': (0, 1, 4, 7),
    '..OX.X.XO': (6,),
    '..OX.X.OX': (1,),
    '..OX.OXX.': (0, 1, 4, 8),
    '..OX.OX.X': (7,),
    '..OX..XXO': (0,),
    '..OX..XOX': (0, 1, 4, 5),
    '..OOXX.X.': (6,),
    '..OOX.XX.': (0, 1, 5, 8),
    '..OOX.X.X': (0, 1, 5, 7),
    '..OOX..XX': (0,),
    '..OO.XXX.': (4,),
    '..OO.XX.X': (4,),
    '..OO.X.XX': (4,),
    '..OO..XXX': (4,),
    '..O.XXOX.': (8,),
    '..O.XXO.X': (0, 1, 3, 7),
    '..O.XX.XO': (6,),
    '..O.XX.OX': (0, 1, 3, 6),
    '..O.XOXX.': (0,),
    '..O.XOX.X': (0,),
    '..O.XO.XX': (0, 1, 3, 6),
    '..O.X.XXO': (0, 1, 3, 5),
    '..O.X.XOX': (0, 1, 3, 5),
    '..O.X.OXX': (0, 1, 3, 5),
    '..O.OXXX.': (3,),
    '..O.OXX.X': (3,),
    '..O.OX.XX': (3,),
    '..O.O.XXX': (3,),
    '..O..XXXO': (0, 1, 3, 4),
    '..O..XOXX': (0, 1, 3, 4),
    '..O..OXXX': (0, 1, 3, 4),
    '...XOXOX.': (8,),
    '...XOOXX.': (0, 1, 2, 8),
    '...XO.XXO': (0,),
    '...X.XOXO': (2,),
    '...X.OXXO': (1,),
    '...OXXOX.': (0, 1, 8),
    '...OXX.XO': (6,),
    '...OXOXX.': (0,),
    '...OXO.XX': (0,),
    '...OX.XXO': (0, 1, 2, 5),
    '...OX.XOX': (0, 1, 2, 5),
    '...OX.OXX': (0,),
    '...OOXXX.': (2,),
    '...OOX.XX': (2,),
    '...OO.XXX': (2,),
    '...O.XXXO': (0, 1, 2, 4),
    '...O.XXOX': (0, 1, 2, 4),
    '...O.XOXX': (1,),
    '...O.OXXX': (0, 1, 2, 4),
    '....XXOXO': (2,),
    '....XXOOX': (0,),
    '....XOXXO': (1,),
    '....XOXOX': (0, 1, 2, 3),
    '....XOOXX': (0, 1, 2, 3),
    '....OXXXO': (0,),
    '....OXXOX': (0, 1, 2, 3),
    '....OXOXX': (0, 1, 2, 3),
    '....OOXXX': (0, 1, 2, 3),
    'OOX.X.XO.': (3, 5, 8),
    'O.XOXOX..': (8,),
    'O.XOX.XO.': (5, 8),
    'O.XOX.OX.': (1, 5, 8),
    'O.XOOXX..': (8,),
    'O.XOO.XX.': (8,),
    'O.X.XOXO.': (3, 8),
    'O.X.XOX.O': (3,),
    'O.X.XOOX.': (3,),
    'O.X.X.XOO': (3, 5),
    'O.X.X.OXO': (3,),
    'O.X.OXOX.': (8,),
    'O.X.OOXX.': (8,),
    'O.OXO.XX.': (8,),
    'O.OOX.XX.': (5,),
    'O.O.XXOX.': (1, 3, 8),
    'O.O.XOXX.': (1,),
    'O.O.XOX.X': (1,),
    'O.O.X.XXO': (5,),
    'O.O.X.XOX': (5,),
    'O.O.X.OXX': (3,),
    'O.O.OXXX.': (1, 3, 8),
    'O.O.O.XXX': (3,),
    '.XO.XOOX.': (8,),
    '.XO.OXOX.': (8,),
    '.XO.OOXX.': (0,),
    '.XO.O.XXO': (0,),
    '.XO.O.OXX': (3, 5),
    '.X.XO.OXO': (0, 2, 5),
    '.OXXO.OX.': (8,),
    '.OXOXO.X.': (8,),
    '.OXOX.OX.': (0, 5, 8),
    '.OXOOX.X.': (6,),
    '.OXOO.XX.': (0, 8),
    '.OXO.XOX.': (0, 4, 8),
    '.OXO.X.XO': (6,),
    '.OXO.OXX.': (0, 8),
    '.OX.XOXO.': (3, 8),
    '.OX.XOOX.': (3,),
    '.OX.X.XOO': (3, 5),
    '.OX.X.OXO': (3,),
    '.OX.OXXO.': (8,),
    '.OX.OXOX.': (0, 3, 8),
    '.OX.OX.XO': (0,),
    '.OX.OOXX.': (0, 8),
    '.OX.O.XXO': (0,),
    '.OX.O.OXX': (3,),
    '.OOXXO.X.': (8,),
    '.OOXX.XO.': (5,),
    '.OOXX.OX.': (8,),
    '.OOXOX.X.': (8,),
    '.OOXO.XX.': (0, 8),
    '.OOX.XXO.': (4,),
    '.OOX.XOX.': (8,),
    '.OOX.X.XO': (0, 4, 6),
    '.OOX.OXX.': (0, 8),
    '.OOOXX.X.': (6,),
    '.OOOX.XX.': (0, 5),
    '.OOO.XXX.': (0, 4),
    '.OOO.X.XX': (0, 4, 6),
    '.OO.XXOX.': (0, 3, 8),
    '.OO.XX.XO': (6,),
    '.OO.XOXX.': (0,),
    '.OO.XO.XX': (0, 3),
    '.OO.X.XXO': (0, 5),
    '.OO.X.XOX': (0, 5),
    '.OO.X.OXX': (0, 3),
    '.OO.OXXX.': (0,),
    '.OO.OX.XX': (3,),
    '.OO.O.XXX': (0, 3),
    '.O.XOXOX.': (8,),
    '.O.XOOXX.': (0, 8),
    '.O.XO.XXO': (0,),
    '.O.X.XOXO': (2,),
    '.O.OXXOX.': (0, 2, 8),
    '.O.OXX.XO': (6,),
    '.O.OXOXX.': (0,),
    '.O.OXO.XX': (0,),
    '.O.OX.XXO': (0, 5),
    '.O.OX.XOX': (0, 2, 5),
    '.O.OX.OXX': (0,),
    '.O.OOXXX.': (0,),
    '.O.OOX.XX': (2,),
    '.O.OO.XXX': (0, 2),
    '.O.O.XXXO': (0, 4),
    '.O.O.XOXX': (0, 2, 4),
    '.O.O.OXXX': (0, 2),
    '..XXOXOO.': (0,),
    '..XXOX.OO': (0,),
    '..XXOOXO.': (8,),
    '..XXOO.XO': (0, 1, 6),
    '..XXOO.OX': (6,),
    '..XXO.XOO': (0,),
    '..XXO.OXO': (0, 1, 5),
    '..XXO.OOX': (0, 1, 5),
    '..XX.XOOO': (4,),
    '..XX.OXOO': (4,),
    '..XX.OOXO': (4,),
    '..XX.OOOX': (4,),
    '..XOXXOO.': (0, 1, 8),
    '..XOXOXO.': (8,),
    '..XOXOX.O': (0, 1, 7),
    '..XOXOOX.': (0,),
    '..XOXO.XO': (1,),
    '..XOXO.OX': (0, 6),
    '..XOX.OXO': (0, 1, 5),
    '..XOX.OOX': (0,),
    '..XOOXXO.': (8,),
    '..XOOXX.O': (0, 1, 7),
    '..XOOXOX.': (1,),
    '..XOOX.XO': (0,),
    '..XOOX.OX': (1, 6),
    '..XOOOXX.': (0, 8),
    '..XOOO.XX': (6,),
    '..XOO.XXO': (0,),
    '..XOO.OXX': (5,),
    '..XO.XOXO': (0, 1, 4),
    '..XO.XOOX': (1,),
    '..XO.OXXO': (0,),
    '..XO.OOXX': (4,),
    '..X.XXOOO': (3,),
    '..X.XOXOO': (3,),
    '..X.XOOXO': (3,),
    '..X.XOOOX': (0, 3),
    '..X.OXXOO': (0, 1, 3),
    '..X.OXOXO': (0,),
    '..X.OXOOX': (1,),
    '..X.OOXXO': (0,),
    '..OXXXOO.': (0, 1, 8),
    '..OXXX.OO': (6,),
    '..OXXOXO.': (0, 1, 8),
    '..OXXOX.O': (1,),
    '..OXXOOX.': (8,),
    '..OXXO.XO': (0, 1, 6),
    '..OXXO.OX': (0,),
    '..OXX.XOO': (5,),
    '..OXX.OOX': (0,),
    '..OXOXXO.': (0, 1, 8),
    '..OXOXX.O': (0,),
    '..OXOXOX.': (8,),
    '..OXOXO.X': (1, 7),
    '..OXOX.XO': (0, 1, 6),
    '..OXOX.OX': (1,),
    '..OXOOXX.': (0, 8),
    '..OXOOX.X': (7,),
    '..OXO.XXO': (0,),
    '..OXO.XOX': (0, 1, 5),
    '..OX.XXOO': (4,),
    '..OX.XOOX': (1,),
    '..OX.OXXO': (0,),
    '..OX.OXOX': (0, 1, 4),
    '..OOXXOX.': (8,),
    '..OOXXO.X': (0, 1),
    '..OOXX.XO': (6,),
    '..OOXX.OX': (0, 1, 6),
    '..OOXOXX.': (0,),
    '..OOXOX.X': (0,),
    '..OOXO.XX': (0,),
    '..OOX.XXO': (0, 5),
    '..OOX.XOX': (0, 5),
    '..OOX.OXX': (0,),
    '..OO.XXXO': (0, 4),
    '..OO.XXOX': (1, 4),
    '..OO.XOXX': (1,),
    '..OO.OXXX': (0,),
    '..O.XXOOX': (0, 1),
    '..O.XOXXO': (0,),
    '..O.XOXOX': (0,),
    '..O.XOOXX': (0, 3),
    '..O.OXXXO': (0,),
    '..O.OXXOX': (1,),
    '..O.OXOXX': (1, 3),
    '..O.OOXXX': (0, 3),
    '...XOXOXO': (0, 1, 2),
    '...XOOXXO': (0,),
    '...OXXOXO': (2,),
    '...OXOXXO': (0,),
    '...OXOXOX': (0, 2),
    '...OXOOXX': (0,),
    '...OOXXXO': (0,),
    '...OOXXOX': (1, 2),
    '...OOXOXX': (1,),
    '...OOOXXX': (0, 2),
    'X.XOXOXO.': (8,),
    'X.X.XOXOO': (1, 3),
    'OOXOX.XX.': (5, 8),
    'OOX.XXOX.': (3,),
    'OOX.XOXX.': (8,),
    'OOX.X.XXO': (5,),
    'O.XXOXXO.': (8,),
    'O.XXOXOX.': (8,),
    'O.XXOOXX.': (8,),
    'O.XOXXOX.': (1, 8),
    'O.XOXOXX.': (8,),
    'O.XOX.XXO': (5,),
    'O.XOX.OXX': (1, 5),
    'O.XOOXXX.': (8,),
    'O.X.XXOXO': (3,),
    'O.X.XOXXO': (1,),
    'O.X.XOOXX': (3,),
    'O.X.OXOXX': (1, 3),
    'O.OXXOXX.': (1,),
    'O.OXX.XXO': (1,),
    'O.OXOXXX.': (1, 8),
    'O.OOX.XXX': (1,),
    'O.O.XXOXX': (1,),
    'O.O.XOXXX': (1,),
    'O.O.OXXXX': (1, 3),
    '.XXOOOXX.': (0, 8),
    '.XX.OOXXO': (0,),
    '.XOXOXOX.': (8,),
    '.XOXOOXX.': (0, 8),
    '.XOXO.XXO': (0,),
    '.XOOXXOX.': (8,),
    '.XOOXOXX.': (0,),
    '.XOOX.XXO': (0, 5),
    '.XO.XOXXO': (0,),
    '.XO.XOOXX': (0, 3),
    '.XO.OXXXO': (0, 3),
    '.XO.OOXXX': (3,),
    '.X.XOXOXO': (0, 2),
    '.X.XOOXXO': (0,),
    '.OXXOXXO.': (8,),
    '.OXXOXOX.': (8,),
    '.OXXOX.XO': (0,),
    '.OXXOOXX.': (8,),
    '.OXXO.XXO': (0, 5),
    '.OXX.XXOO': (4,),
    '.OXX.XOXO': (4,),
    '.OXOXXOX.': (0, 8),
    '.OXOXX.XO': (6,),
    '.OXOXOXX.': (8,),
    '.OXOXO.XX': (0, 6),
    '.OXOX.XXO': (5,),
    '.OXOX.OXX': (0,),
    '.OXOOXXX.': (0, 8),
    '.OXOOX.XX': (6,),
    '.OXO.XXXO': (0, 4),
    '.OXO.XOXX': (0, 4),
    '.OX.XXOXO': (3,),
    '.OX.XOOXX': (0, 3),
    '.OX.OXXXO': (0,),
    '.OX.OXOXX': (3,),
    '.OOXXXOX.': (0, 8),
    '.OOXXX.XO': (0, 6),
    '.OOXXOXX.': (0, 8),
    '.OOXX.XXO': (0, 5),
    '.OOXX.XOX': (0,),
    '.OOXOXXX.': (0,),
    '.OOX.XXXO': (0,),
    '.OOX.XXOX': (0,),
    '.OOOXX.XX': (0,),
    '.OOOX.XXX': (0,),
    '.OOO.XXXX': (0, 4),
    '.OO.XXOXX': (0,),
    '.OO.XOXXX': (0,),
    '.OO.OXXXX': (0, 3),
    '.O.XOXXXO': (0,),
    '.O.OXXOXX': (0,),
    '.O.OXOXXX': (0, 2),
    '.O.OOXXXX': (2,),
    '..XXOXXOO': (0,),
    '..XXOXOXO': (0,),
    '..XXOXOOX': (0,),
    '..XXOOXXO': (0, 1),
    '..XOXXOXO': (0, 1),
    '..XOXXOOX': (0,),
    '..XOXOXXO': (1,),
    '..XOXOOXX': (0,),
    '..XOOXXXO': (0,),
    '..XOOXOXX': (1,),
    '..OXXXOOX': (0,),
    '..OXXOXXO': (1,),
    '..OXXOXOX': (0,),
    '..OXOXXXO': (0,),
    '..OXOXXOX': (1,),
    '..OOXXOXX': (0, 1),
    '..OOXOXXX': (0,),
    'XOXOXOXO.': (8,),
    'OXOXOXOX.': (8,),
    'OOXXOXXO.': (8,),
    'OOXXOXOX.': (8,),
    'OOXXOOXX.': (8,),
    'OOXOXXOX.': (8,),
    'OOXOXOXX.': (8,),
    'OOXOX.XXO': (5,),
    'OOXOOXXX.': (8,),
    'OOX.XXOXO': (3,),
    'OOX.XOOXX': (3,),
    'O.XOXXOXO': (1,),
    'O.XOXOXXO': (1,),
    'O.XOXOOXX': (1,),
    'O.XOOXOXX': (1,),
    'O.OXXOXXO': (1,),
    'O.OOXXOXX': (1,),
    'O.OOXOXXX': (1,),
    '.XXOOOXXO': (0,),
    '.XOXOOXXO': (0,),
    '.XOOXOXXO': (0,),
    '.XOOXOOXX': (0,),
    '.OXXOXXOO': (0,),
    '.OXXOXOXO': (0,),
    '.OXOXXOXO': (0,),
    '.OXOXOOXX': (0,),
    '.OXOOXXXO': (0,),
    '.OXOOXOXX': (0,),
    '.OOXXXOOX': (0,),
    '.OOXXOXOX': (0,),
    '.OOXOXXXO': (0,),
    '.OOXOXXOX': (0,),
    '.OOOXXOXX': (0,),
    '.OOOXOXXX': (0,),
}

C2L = {0: 0, 1: 1, 2: 2, 3: 5, 4: 8, 5: 7, 6: 6, 7: 3, 8: 4}  # cycle rep to line rep


def _rot(s, r):
    's:cycle-state'
    return s[r:-1]+s[:r]+s[-1]


def _refl(s):
    return s[0] + s[-2:-5:-1] + s[4] + s[3:0:-1] + s[8]


def canonic(s):
    '''returns a canonical cycle rep.
       playing at i in the canonical rep corresponds to
       playing transform(rot, refl, i) in the original cycle rep.
    '''
    t = _refl(s)
    rs = [(_rot(s, r), (-r, False)) for r in (0, 2, 4, 6)]
    rt = [(_rot(t, r), (-r, True)) for r in (0, 2, 4, 6)]
    return min(rs+rt)


def tfb(rot, refl, i):
    if i == 8:
        return 8
    i = i - rot
    if refl:
        i = 8-i
    return i % 8


def l2c(s):
    'line rep to circle rep'
    return s[:3] + s[5] + s[-1:-4:-1] + s[3] + s[4]


def get_good_moves(s):
    t, tf = canonic(l2c(s))
    moves = position_moves[t]
    moves = [C2L[tfb(*tf, i)] for i in moves]
    return moves